/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    FactoryGraph: typeof import('./components/FactoryGraph.vue')['default']
    GraphEdge: typeof import('./components/GraphEdge.vue')['default']
    GraphNode: typeof import('./components/GraphNode.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ItemCard: typeof import('./components/ItemCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
